# Generated by Django 5.0.6 on 2024-05-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meerut_zone_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='category',
            field=models.CharField(choices=[('Nursing homes', 'Nursing homes'), ('EYE hospitals', 'EYE hospitals'), ('Blood banks', 'Blood banks'), ('General Medical & Surgical Hospitals', 'General Medical & Surgical Hospitals'), ('Neurology', 'Neurology')], max_length=200),
        ),
    ]
