# Generated by Django 5.0.6 on 2024-05-21 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meerut_zone_app', '0005_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='message',
            new_name='Messages',
        ),
    ]
