# Generated by Django 5.0.6 on 2024-05-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meerut_zone_app', '0006_rename_message_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('post', models.CharField(max_length=200)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
    ]
